### ISSUE TITLE
python.exe stops execution

### ISSUE THREAD

**Issue by buurkeey** [workshare/parallel_pybot#3]
When I send python ppybot.py commadn on cmd, I got an error on Windows 7(Python 2.7.6).
The error is:

Cannot execute /usr/local/bin/pybot - please check your configuration / parameters
The runtime is not correctly configured - I cannot run :(

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by bbossola** [comment]
You need to specify the folder where the tests are :) If it's the current
folder, just digit:
python ppybot.py .

**Comment by bbossola** [comment]
Ah, now I see... sorry, I misread it. You are using Windows! See the specific configuration in the ppybot_config.py: comment the linux lines and uncomment the windows ones

**Comment by gjungberg** [comment]
Hi,
Im getting the following error:

C:\Automation>python ppybot.py c:\Automation\FM1\
Robot Framework 2.9a1 (Python 2.7.10 on win32)
rebot.bat - please check your configuration / parameters
The runtime is not correctly configured - I cannot run :(

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Any help?


Whats

**Comment by bbossola** [comment]
The script is unable to execute pybot or rebot, either because they cannot be found or they are not executable. The script locates them based on what's written inside the [ppybot_config.py](/workshare/parallel_pybot/blob/master/ppybot_config.py)

[ppybot_config.py](/workshare/parallel_pybot/blob/master/ppybot_config.py) comes with a "typical Linux configuration", so if you are using Windows you should comment that out and uncomment the "typical Windows configuration". At that time, please double check that pybot and rebot are exactly in those locations.

This should solve your issue.

**Comment by gjungberg** [comment]
I double checked my configuration. Maybe there is some kind of issue on compatibility? .
